# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: docker://ghcr.io/pilab-dev/container-prebuilt-action:v0.2.0
  # image: 'Dockerfile'
  # args:
  #   - ${{ inputs.who-to-greet }}
  env:
    GREETING: 'Hello'
    WHO_TO_GREET: ${{ inputs.who-to-greet }}